### ISSUE TITLE
Docs colors

### ISSUE THREAD

**Issue by zacanger** [jane/jane-components#21]
Right now the docs mostly use the default colors. We could make them a little more pleasant. Resources:

* <https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-styles-of-a-style-guide>
* <https://github.com/styleguidist/react-styleguidist/blob/master/src/styles/theme.js>

**Comment by jhelst** [comment]
I can tinker with something. I'll try not to make it too distracting, so the components are the focus.

**Comment by jhelst** [comment]
https://github.com/jane/jane-components/pull/30
